# Generated by Django 6.0.7 on 2026-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('HIGH_RISK_ZONE', 'High Risk Zone Warning'), ('INCIDENT_BROADCAST', 'Incident Broadcast'), ('SECURITY_DISPATCH', 'Security Dispatch')], default='HIGH_RISK_ZONE', max_length=50)),
                ('location_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
